=== princehaku/railgun/trunk/sites/shell.xsd
<?xml version="1.0"?>
<!-- 
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" xmlns="http://railgun.techest.net" targetNamespace="http://railgun.techest.net">
    <xs:element name="shell">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="description"  type="xs:string" />
                <xs:element name="baseurl" type="xs:string" minOccurs="0"/>
                <xs:element name="reloadtime" type="xs:integer" minOccurs="0"/>
                <xs:element name="stair" type="stair" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="stair">    
        <xs:all>
            <xs:element name="fetch" type="fetch" minOccurs="0"/>
            <xs:element name="stair" type="stair" minOccurs="0"/>
            <xs:element name="print" minOccurs="0"/>
            <xs:element name="handler" minOccurs="0"/>
            <xs:element name="parse" type="parse" minOccurs="0" />
            <xs:element name="filestore" type="filestore" minOccurs="0" />
            <xs:element name="dbstore" type="dbstore" minOccurs="0" />
        </xs:all>
        <xs:attribute name="fork">
            <xs:simpleType>
                <xs:restriction base="xs:boolean">
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="reset">
            <xs:simpleType>
                <xs:restriction base="xs:boolean">
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- START FOR FETCH-->
    <xs:complexType name="fetch">
        <xs:all>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="method" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="post"/>
                        <xs:enumeration value="get"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="charset" type="xs:string" minOccurs="0"/>
            <xs:element name="timeout" type="xs:integer" minOccurs="0"/>
            <xs:element name="params" type="params" minOccurs="0"/>
            <xs:element name="cookie" type="xs:boolean" minOccurs="0"/>
            <xs:element name="cookies" type="cookies" minOccurs="0"/>
            <xs:element name="content" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="params">
        <xs:sequence>
            <xs:element name="param" type="param" minOccurs="1"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="param">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="cookies">
        <xs:sequence>
            <xs:element name="cookie" type="cookie" minOccurs="1"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="cookie">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <!-- END FOR FETCH-->
    
    
    <!-- START FOR PARSE-->
    <xs:complexType name="parse">
        <xs:all>
            <xs:element name="rule" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:all>
        <xs:attribute name="method">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="regxp"/>
                    <xs:enumeration value="dom"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <!-- END FOR PARSE-->
    
    <!-- START FOR FILESTORE-->
    <xs:complexType name="filestore">
        <xs:all>
            <xs:element name="path" type="xs:string" minOccurs="1"/>
            <xs:element name="data" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <!-- END FOR FILESTORE-->
    
    <!-- START FOR DBSTORE-->
    <xs:complexType name="dbstore">
        <xs:sequence>
            <xs:element name="resource" type="resource" minOccurs="1"/>
            <xs:element name="form" type="form" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="resource">
        <xs:attribute name="url" type="xs:string" use="required"/>
        <xs:attribute name="driverClassName" type="xs:string" use="required"/>
        <xs:attribute name="username " type="xs:string" use="required"/>
        <xs:attribute name="password" type="xs:string" use="required"/>
        <xs:attribute name="maxActive" type="xs:integer"/>
        <xs:attribute name="maxWait" type="xs:integer"/>
        <xs:attribute name="maxIdle" type="xs:integer"/>
    </xs:complexType>
    <!-- END FOR DBSTORE-->
    
</xs:schema>

=== princehaku/railgun/trunk/src/main/java/testtask1.xml
<?xml version="1.0" encoding="UTF-8"?>
<shell xmlns="http://railgun.techest.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://railgun.techest.net shell.xsd">
    <name>oabt</name>
    <description>无极电影抓取</description>
    <baseurl>*</baseurl>
    <reloadtime>10000</reloadtime>
    <stair>
        <fetch>
            <url>http://oabt.org/?page=$[1,3]</url>
        </fetch>
        <parse method="dom">
            <rule>.toplist tbody</rule>
        </parse>
        <handler>net.techest.railgun.test.TestFilter</handler>
    </stair>
</shell>

=== princehaku/railgun/trunk/sites/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<shell xmlns="http://railgun.techest.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://railgun.techest.net shell.xsd">
    <name>oabt</name>
    <description>test</description>
    <baseurl>*</baseurl>
    <reloadtime>3600000</reloadtime>
    <stair>
        <fetch>
            <url>http://localhost:8888/$[100,300]</url>
            <cookies>
                <cookie-string>time=$time</cookie-string>
             </cookies>
        </fetch>
    </stair>
</shell>

=== princehaku/railgun/trunk/sites/oabt.org.xml
<?xml version="1.0" encoding="UTF-8"?>
<shell xmlns="http://railgun.techest.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://railgun.techest.net shell.xsd">
    <name>oabt</name>
    <description>我爱P2P电影抓取</description>
    <baseurl>*</baseurl>
    <reloadtime>10000</reloadtime>
    <stair>
        <fetch>
            <url>http://oabt.org/?page=$[1,2]</url>
        </fetch>
        <parse method="dom">
            <rule>.toplist tbody</rule>
        </parse>
        <parse method="regxp">
            <rule>href="(.*?)"</rule>
        </parse>
    </stair>
</shell>
